spring:
  application:
    name: xinguan-base-web

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://changyw:3306/xinguan?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: changyw
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 连接只读数据库时配置为true， 保证安全
      read-only: false
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-timeout: 30000
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 600000
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
      max-lifetime: 1800000
      # 连接池中允许的最大连接数。缺省值：10
      maximum-pool-size: 60
      minimum-idle: 10
#    druid:
#      initial-size: 5
#      max-active: 30
#      min-idle: 5
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 50
#      filters: stat,wall
#      use-global-data-source-stat: true


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  security:
    user:
      name: changyw
      password: 123456

server:
  port: 8081


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: top.chang888.system.entity

alioss:
  endpoint: oss-cn-shanghai.aliyuncs.com
  accessKeyId: LTAI5tMXvCuxnAaZR6DE6bEk
  accessKeySecret: lEmcn6SCUy5eNGvkhdOrjjXuqjkD7m
  bucketName: admin-parent